- name: Download and install docker
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install docker
  ansible.builtin.dnf:
    name: docker-ce
    state: installed

- name: Start docker
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true

- name: Create a docker container
  loop:
    - runner-1
    - runner-2
    - runner-3
  community.docker.docker_container:
    name: {{ item }}
    image: ng1218/github-runner
    state: present
    recreate: true
    pull: always
    env:
      ORG: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/github-runner:ORG token={{ token }} url=http://vault.nareshdevops1218.online:8200') }}"
      TOKEN: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/github-runner:TOKEN token={{ token }} url=http://vault.nareshdevops1218.online:8200') }}"

